# Generated by Django 2.2.6 on 2021-07-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стадия')),
                ('match_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('match_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место проведения')),
                ('home_team_title', models.CharField(max_length=255, verbose_name='Команда 1')),
                ('away_team_title', models.CharField(max_length=255, verbose_name='Команда 2')),
                ('home_team_id', models.CharField(default='', max_length=255, verbose_name='ID команды 1')),
                ('away_team_id', models.CharField(default='', max_length=255, verbose_name='ID команды 2')),
                ('home_team_score_ft', models.IntegerField(blank=True, null=True, verbose_name='Голы команды 1')),
                ('away_team_score_ft', models.IntegerField(blank=True, null=True, verbose_name='Голы команды 2')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'livescore_match',
            },
        ),
    ]
