# Generated by Django 2.2.6 on 2021-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_title', models.CharField(max_length=255, verbose_name='Команда 1')),
                ('away_team_title', models.CharField(max_length=255, verbose_name='Команда 2')),
                ('home_team_score_ft', models.IntegerField(blank=True, null=True, verbose_name='Голы команды 1')),
                ('away_team_score_ft', models.IntegerField(blank=True, null=True, verbose_name='Голы команды 2')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'result',
            },
        ),
    ]
