# Generated by Django 2.2.6 on 2021-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livescore', '0005_result_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='away_team_id',
            field=models.CharField(default='', max_length=255, verbose_name='ID команды 2'),
        ),
        migrations.AddField(
            model_name='result',
            name='home_team_id',
            field=models.CharField(default='', max_length=255, verbose_name='ID команды 1'),
        ),
    ]
